---
- name: Install and mount LVM volume
  hosts: all

  vars:
    smb_conf: ./smb.conf

  tasks:
  - name: disable firewalld
    shell: systemctl disable --now firewalld

  - name: disable selinux
    shell: sed -i "s/SELINUX=enforcing/SELINUX=disabled/g" /etc/selinux/config

  - name: set the reboot
    reboot:
      reboot_timeout: 300

  - name: install mdadm
    dnf: name=mdadm state=installed

  - name: mdadm
    shell: mdadm --zero-superblock --force /dev/sdb && mdadm --zero-superblock --force /dev/sdc && mdadm --zero-superblock --force /dev/sdd &&  mdadm --zero-superblock --force /dev/sde

  - name: wipefs
    shell: wipefs --all --force /dev/sdb && wipefs --all --force /dev/sdc && wipefs --all --force /dev/sdd && wipefs --all --force /dev/sde

  - name: mdadm create raid
    shell: echo "y" | mdadm --create --verbose /dev/md0 -l 1 -n 4 /dev/sdb /dev/sdc /dev/sdd /dev/sde

  - name: pvcreate
    shell: pvcreate /dev/md0
    when: inventory_hostname == "Ansible"

  - name: vgcreate
    shell: vgcreate LVM /dev/md0
    when: inventory_hostname == "Ansible"

  - name: lvcreate
    shell: lvcreate -n LVM-smb -l 50%FREE LVM
    when: inventory_hostname == "Ansible"

  - name: mkfs.ext4
    shell: mkfs.ext4 /dev/LVM/LVM-smb
    when: inventory_hostname == "Ansible"

  - name: mkdir for lvm
    shell: mkdir /opt/lvm
    when: inventory_hostname == "Ansible"

  - name: automount
    shell: echo "/dev/LVM/LVM-smb    /opt/lvm    ext4    defaults    0  0" >> /etc/fstab
    when: inventory_hostname == "Ansible"

  - name: mount -a
    shell: mount -a
    when: inventory_hostname == "Ansible"

  - name: install samba
    yum: name=samba state=installed
    when: inventory_hostname == "Ansible"

  - name: change the samba config file
    copy: src={{ smb_conf }}  dest=/etc/samba/smb.conf
    when: inventory_hostname == "Ansible"

  - name: smbpasswd -a
    shell: (echo "toor"; echo "toor") | smbpasswd -s -a "root"
    when: inventory_hostname == "Ansible"

  - name: start and enable samba.service
    service: name=smb state=started enabled=yes
    when: inventory_hostname == "Ansible"

  - name: install samba-client
    yum: name=samba-client state=installed

  - name: mkdir
    shell: mkdir /opt/LVM
    when: inventory_hostname != "Ansible"

  - name: mount lvm for /opt/LVM
    shell: echo "//{{ lvm_serv_ip }}/lvm    /opt/LVM  cifs   username=root,password=toor,dir_mode=0777,file_mode=0777    0 0" >> /etc/fstab
    when: inventory_hostname != "Ansible"

  - name: mount -a
    shell: mount -a
    when: inventory_hostname != "Ansible"
